### ISSUE TITLE
Please merge the nnethercote and nnethercote2 users

### ISSUE THREAD

**Issue by nnethercote** [mozilla/standup#414] opened 2017-07-23 23:38 UTC
I accidentally create a second standu.ps account. I think this is because I was using my GitHub login and then I forgot about that and logged in via LDAP, which apparently caused the nnethercote2 account to be created.

If you could merge them that would be great. Thank you.

**Comment by willkg** [comment] 2017-07-24 21:12
I moved the status items, but hit an issue when removing the actual nnethercote2 account. That's covered in #415.

As soon as someone/me fixes that, I can finish this one up.

**Comment by nnethercote** [comment] 2017-07-24 23:16
Thank you for merging the entries.

I just logged in again. I had to clear all the standu.ps cookies because Firefox was complaining about the page being set up in a way that would never resolve loading, or something like that.

Anyway, after logging in I was presented with a page that said "Welcome to Standup! Before you can start kicking it with your peeps on Standup, you must fill out a profile." (It populated the form with my email address and "nnethercote3" as the "URL slug".) But this is completely false! I already have an account, and I'm logged in, and if I hit "save changes" on that form, AFAICT it'll create another account. I think that's how I ended up with the nnethercote2 account in the first place. It's very confusing and easy to get wrong.

**Comment by willkg** [comment] 2017-07-24 23:56
So, there are a couple of possibilities:

1. you're logging in with the Mozilla SSO using multiple accounts
2. the email address associated with the way you're logging in with Mozilla SSO has changed, so when Standups goes to connect the Mozilla SSO identity with the Standup identity, it thinks you're new
3. some third thing

Right now, you've got the following three accounts:

```
user_id  username                     email                    name                 slug          irc  # statuses  last login                        created
323      nnethercote                  nnethercote@mozilla.com  Nicholas Nethercote  nnethercote   njn  33          2017-07-23 23:31:50.181365+00:00  2016-11-08 05:40:19.737725+00:00
515      3CoJhym0XbGy53AX9Slj9rVV--c  nnethercote@mozilla.com                       nnethercote2       0           2017-07-23 23:29:40.023771+00:00  2017-05-21 23:05:14.811552+00:00
537      sBMl6Jr7uSAdcFeq86wWQfTSP5A  n.nethercote@gmail.com                        nnethercote3       0           2017-07-24 23:12:25.444149+00:00  2017-07-24 23:12:25.258313+00:00
```

515 will go away once I fix #415.

537 is the new one--that's got a gmail.com email address, so I think you logged into Mozilla SSO differently. We have no control over login after you leave the Standup site, so any UX issues you encounter are Mozilla SSO UX issues. We have an intermediate page which we can add instructions to, but I'm not sure what we can say to make logging in less confusing. I'm game for suggestions!

Regarding the "Firefox was complaining about the page being set up in a way that would never resolve loading" issue, only you and someone else get that--no one else. I've never been able to reproduce it, so it's hard to look into. It's frustrating. That's covered in #412, so if you have more details, please add a comment there.

**Comment by nnethercote** [comment] 2017-07-25 00:21
So I actually created an nnethercote3 account? Good grief. I'm not trying to be difficult, I promise! :)

**Comment by willkg** [comment] 2017-07-25 01:14
I think I messed up. You were using the gmail.com address with your original account. I merged the mozilla.com address into the gmail.com one, so that overrode the email address in the original account to the mozilla.com address. But since you use your gmail.com address, when you went to log in again, you got a third account. That's totally my fault--I didn't read your plight carefully enough.

I've fixed that now (or rather half-fixed it, because #415 is still a problem). Let me know if you're still having problems. Super sorry about that!

I spent some more time looking at #412. Knowing it's happening to multiple people and long after we switched to mozilla-django-oidc is interesting. I wrote up a theory in the comments of the mozilla-django-oidc issue with some fixes we should probably do regardless of whether the theory is correct. I'll try to move forward on that soon.

**Comment by nnethercote** [comment] 2017-07-25 02:12
@willkg: so should I login with my GitHub credentials now or my LDAP credentials?

**Comment by willkg** [comment] 2017-07-25 02:23
GitHub assuming that is your gmail.com address.

**Comment by nnethercote** [comment] 2017-07-25 02:32
Ok, GitHub seems to be working. Upon login, it takes me to my profile, which says
```
Your profile

If you think you already have an account with a profile, then log out and let us know. We can check the database and merge your accounts.

If you need to change your email address, let us know. 
```
Followed by the form which is populated with my details.

So it no longer has the "kicking it with your peeps" text, which is good. But I still find it confusing to be confronted by this form upon logging in; I keep thinking I need to fill it in. It would be less surprising if it took me straight to my recent entries at https://www.standu.ps/user/nnethercote/.

**Comment by willkg** [comment] 2017-07-25 14:38
@nnethercote I thought there was an issue covering figuring out a better flow post-login, but there isn't. Can you write a new one up and move the conversation there?

**Comment by nnethercote** [comment] 2017-07-26 04:40
I filed #418.

**Comment by willkg** [comment] 2017-07-26 14:49
I removed the incorrect account, so I think we're all done here. Closing this out.

**Comment by nnethercote** [comment] 2017-09-10 23:16
Hi again. Somehow the nnethercote2 account has come back, and the entries from August that had been merged into the nnethercote account are back with the nnethercote2 account again.

**Comment by willkg** [comment] 2017-09-12 21:07
Sorry that took so long. I ended up fixing the mergeuser command that I was using. But to do that, I had to fix a deploy issue. Bleh.

You should be all set.

Further, I wrote up issue #425. I think fixing that will alleviate this problem. The underlying issue is that you're using multiple accounts with a single SSO that covers a bunch of different systems and has UX that "helps" you by making it easy to use the same SSO account. I think that's what's going on. We can talk about that more in #425.

**Comment by nnethercote** [comment] 2017-09-17 23:03
Sorry to bother you again, but...

I just went to www.standu.ps. It took me to the nnethercote2 profile page; that account is back again. I suspect that my nnethercote@mozilla.com logins from other sites are somehow propagating to standu.ps. This time I realized what had happened, so I logged out and logged into the nnethercote account (the GitHub credentials one).

**Comment by willkg** [comment] 2017-09-17 23:43
It's totally not your fault! I'm pretty sure working on #425 should alleviate the problems. I'm just swamped and haven't had a chance to work on it, yet.

**Comment by willkg** [comment] 2017-09-18 15:24
I merged the two accounts. You should be all set again for now.

**Closed by willkg** 2017-09-18 15:24 UTC
Labels: in-progress, support
