### ISSUE TITLE
Got "You must be signed in to view your profile. Please sign in and try again." when signing-in with Github account

### ISSUE THREAD

**Issue by freesamael** [mozilla/standup#287] opened 2016-11-30 18:50 UTC
Reproduce steps:
1. Go to https://www.standu.ps/login/
2. Press Sign-in with Github.
3. Login to github account.

Result:
It redirects back to https://www.standu.ps/login/ with a message "You must be signed in to view your profile. Please sign in and try again."

Not all github accounts have the issue. I can reproduce that with a newly created test account "freesamael-test". Somehow every time I use that account to sign-in, it redirects to /new-profile/ and then /login/ with the error message above.

**Comment by shes050117** [comment] 2016-12-01 01:48
I have the same issue with this account (shes050117). When I try to sign in Standup with my github account, I get the error message: "You must be signed in to view your profile. Please sign in and try again.".

**Comment by willkg** [comment] 2016-12-01 20:16
I really apologize you and others are running into this. I spent some time looking into this earlier and I don't really understand what's causing the problem. We have a couple of other auth-related things we want to discuss in Hawaii (remove Persona, maybe switch to auth0, etc).

Is it urgent that you log into Standups? Are you able to post from IRC?

If it is urgent, I can spend some more time on it and see if I can figure it out.

If it's not urgent, then I'd like to spend some time in Hawaii sorting out the auth plan with @pmac which will probably fix/alleviate the auth problems we've got.

**Comment by shes050117** [comment] 2016-12-02 01:34
To log into Standups is not urgent to me, but I would like to report my status in Standups. It's fine for me to wait until you sort out the plan and fix the auth problems. Thanks!

**Comment by hiikezoe** [comment] 2016-12-19 23:53
Now #295 had been closed,  what is the current status of this issue?

**Comment by birtles** [comment] 2016-12-20 00:29
A couple of my team have this problem and are unable to post from IRC either (they just get "Uh oh, something went wrong").

**Comment by pmac** [comment] 2016-12-20 00:56
auth0 is implemented and has been successfully tested on our staging instance. As soon as we get the credentials for the prod version of auth0 we'll deploy and hopefully this issue will be fully fixed. Should be this week I hope.

**Comment by birtles** [comment] 2016-12-20 00:56
Great, thank you!

**Comment by willkg** [comment] 2016-12-22 15:10
@birtles @hiikezoe @chihweitung @freesamael I just pushed out changes that ditch Persona and Github auth in favor of Auth0 which lets you use Github to authenticate or a passwordless email code.

Can you try that out and see if you can log in? If you have any problems, let me know.

**Comment by hiikezoe** [comment] 2016-12-22 21:10
@willkg  I just tried it now,  unfortunately I got another error.

"Standup user with this Github handle already exists."

**Comment by willkg** [comment] 2016-12-22 21:11
@hiikezoe Can you be more specific about what you tried? Steps to reproduce would be helpful in understanding the context.

**Comment by hiikezoe** [comment] 2016-12-22 21:43
I tried to log-in with:
Email Adress: hiikezoe@mozilla-japan.org
Name: Hiroyuki Ikezoe
IRC Handle: hiro
Github Handle : hiikezoe

The email address is associated with the github account.  I guess there is my old entry , that I tried before, as a garbage in database.

**Comment by willkg** [comment] 2016-12-22 21:46
@hiikezoe It sounds like you:

1. went to https://www.standu.ps/
2. clicked on the "Sign in" link in the upper right hand corner
3. clicked on the "Sign in with Auth0" button of the sign in page
4. signed in successfully and ended up on the Profile page
5. tried to change something in your profile--maybe the github_handle-- and then hit an error

Does that sound right? If not, what do I have wrong?

**Comment by hiikezoe** [comment] 2016-12-22 21:46
@willkg oops, sorry.  login process seems to be successful. The error happens when I try to edit my profile.

**Comment by willkg** [comment] 2016-12-22 23:44
@hiikezoe Perfect! It means you probably have two accounts (not your fault) and we should merge them. I'll do this tomorrow.

**Comment by hiikezoe** [comment] 2016-12-22 23:46
@willkg thanks!

**Comment by willkg** [comment] 2016-12-22 23:50
@hiikezoe Oh, if you're on I'll do it now....

I found two accounts. Neither had any status items associated with them, so I deleted them both. You should be able to start fresh now.

**Comment by hiikezoe** [comment] 2016-12-22 23:59
@willkg thanks a lot!  Now I could post the first status!  Thank you!
https://www.standu.ps/user/hiikezoe/

**Comment by willkg** [comment] 2017-01-04 17:51
I'm in the process of fixing/improving/rewriting the auth0 support. After that, I can help with fixing accounts. Really sorry about that--it's been tough.

**Comment by willkg** [comment] 2017-01-24 19:41
@birtles @hiikezoe @chihweitung @freesamael I pushed a rewrite of the Auth0 changes.

Is anyone still having problems logging in? If so, can you let me know? If I don't hear anything in the next week, I'll assume everyone is fine and will close this out.

**Comment by chihweitung** [comment] 2017-01-25 01:31
It works fine for me. Thanks!

**Comment by hiikezoe** [comment] 2017-01-25 02:31
I've been using without any authentication problems.

**Comment by willkg** [comment] 2017-02-13 20:56
I think we're all set here. If not, please open up a new issue. Thank you all for your patience as we switched auth systems!

**Closed by willkg** 2017-02-13 20:56 UTC
Labels: in-progress, support
